# Generated by Django 5.2.6 on 2025-10-06 06:01

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('login_id', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='operators/photos/')),
                ('role', models.CharField(choices=[('operator', 'Оператор'), ('supervisor', 'Супервайзер'), ('manager', 'Менеджер')], default='operator', help_text='Должность сотрудника', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('operator', 'Оператор'), ('supervisor', 'Супервайзер'), ('manager', 'Менеджер')], default='operator', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('operator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='hourly_locks.operator')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(help_text='День, когда оператор отрабатывает долг')),
                ('duration', models.DurationField(help_text='Сколько часов должен отработать')),
                ('type', models.CharField(choices=[('compensation', 'Отработка'), ('exception', 'Исключение')], default='compensation', help_text='Тип заявки: отработка или исключение', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждено (полностью)'), ('partial', 'Зачтено частично'), ('declined', 'Отклонено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('deducted', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_compensations', to='hourly_locks.operator')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DurationField(default=datetime.timedelta)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='hourly_locks.operator')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDebtDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('schedule', models.CharField(blank=True, max_length=20, null=True)),
                ('norm_full', models.DurationField(default=datetime.timedelta)),
                ('fact_full', models.DurationField(default=datetime.timedelta)),
                ('debt_full', models.DurationField(default=datetime.timedelta)),
                ('norm_lock', models.DurationField(default=datetime.timedelta)),
                ('fact_lock', models.DurationField(default=datetime.timedelta)),
                ('debt_lock', models.DurationField(default=datetime.timedelta)),
                ('note', models.TextField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_details', to='hourly_locks.operator')),
            ],
        ),
        migrations.CreateModel(
            name='TransferedWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('mismatch', 'Mismatch')], default='pending', max_length=20)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hourly_locks.operator')),
            ],
            options={
                'unique_together': {('operator', 'date_from', 'date_to')},
            },
        ),
        migrations.CreateModel(
            name='WorkLogsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('aftercallduration', models.DurationField(default=0)),
                ('busyduration', models.DurationField(default=0)),
                ('holdduration', models.DurationField(default=0)),
                ('idleduration', models.DurationField(default=0)),
                ('lazyduration', models.DurationField(default=0)),
                ('lockduration', models.DurationField(default=0)),
                ('relaxduration', models.DurationField(default=0)),
                ('fullduration', models.DurationField(default=0)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True, verbose_name='График из Sheets')),
                ('start_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='hourly_locks.operator')),
            ],
            options={
                'unique_together': {('operator', 'day')},
            },
        ),
    ]
