# Generated by Django 5.2.6 on 2025-10-06 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Супервайзер этой группы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_groups', to='hourly_locks.operator')),
            ],
            options={
                'verbose_name': 'Группа операторов',
                'verbose_name_plural': 'Группы операторов',
            },
        ),
        migrations.AddField(
            model_name='operator',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='hourly_locks.group'),
        ),
    ]
