# Generated by Django 5.2.6 on 2025-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0002_group_operator_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='group',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_groups', to='hourly_locks.operator', verbose_name='Супервайзеры'),
        ),
    ]
