# Generated by Django 5.2.6 on 2025-10-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0003_remove_group_supervisor_group_supervisors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='supervisors',
            new_name='supervisor',
        ),
    ]
