# Generated by Django 5.2.6 on 2025-10-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0004_rename_supervisors_group_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='supervisor',
            new_name='supervisors',
        ),
    ]
