# Generated by Django 5.2.6 on 2025-10-06 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0005_rename_supervisor_group_supervisors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='supervisors',
        ),
        migrations.AddField(
            model_name='group',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Супервайзер этой группы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_groups', to='hourly_locks.operator'),
        ),
    ]
