# Generated by Django 5.2.6 on 2025-10-07 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0006_remove_group_supervisors_group_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferedworkday',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Кем зафиксирован'),
        ),
    ]
