# Generated by Django 5.2.6 on 2025-10-08 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0008_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcompensation',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_compensations', to=settings.AUTH_USER_MODEL, verbose_name='Кем зафиксирован'),
        ),
    ]
