# Generated by Django 5.2.6 on 2025-10-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0009_workcompensation_fixed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='group',
            name='supervisors',
            field=models.ManyToManyField(blank=True, help_text='Супервайзер этой группы', related_name='supervised_groups', to='hourly_locks.operator'),
        ),
    ]
