# Generated by Django 5.2.6 on 2025-10-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0010_remove_group_supervisor_group_supervisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdebt',
            name='total_debt_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workdebt',
            name='total_debt_hour',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
    ]
