# Generated by Django 5.2.6 on 2025-10-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0011_workdebt_total_debt_day_workdebt_total_debt_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['surname', 'name']},
        ),
        migrations.AlterField(
            model_name='operator',
            name='login_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='operator',
            name='role',
            field=models.CharField(choices=[('operator', 'Оператор'), ('supervisor', 'Супервайзер'), ('manager', 'Менеджер')], db_index=True, default='operator', help_text='Должность сотрудника', max_length=20),
        ),
        migrations.AlterField(
            model_name='operator',
            name='surname',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['group'], name='hourly_lock_group_i_2d2b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['group', 'login_id'], name='hourly_lock_group_i_5c8464_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['surname', 'name'], name='hourly_lock_surname_3bd763_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['role'], name='hourly_lock_role_4d00ff_idx'),
        ),
    ]
