# Generated by Django 5.2.6 on 2025-10-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0012_alter_operator_options_alter_operator_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcompensation',
            name='chosen_debts',
            field=models.ManyToManyField(related_name='compensations', to='hourly_locks.workdebtdetail'),
        ),
        migrations.AddField(
            model_name='workcompensation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='workcompensation',
            name='screens',
            field=models.ImageField(blank=True, null=True, upload_to='screens/'),
        ),
        migrations.AlterField(
            model_name='workcompensation',
            name='type',
            field=models.CharField(choices=[('compensation', 'Отработка'), ('exception', 'Исключение'), ('no_compensation', 'Не отработает')], default='compensation', help_text='Тип заявки:', max_length=20),
        ),
    ]
