# Generated by Django 5.2.6 on 2025-10-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0013_workcompensation_chosen_debts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcompensation',
            name='chosen_debts',
        ),
    ]
