# Generated by Django 5.2.6 on 2025-10-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0014_remove_workcompensation_chosen_debts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcompensation',
            name='related_debts',
            field=models.ManyToManyField(blank=True, help_text='Нарушения, покрываемые данной отработкой', related_name='compensations', to='hourly_locks.workdebtdetail'),
        ),
    ]
