# Generated by Django 5.2.6 on 2025-10-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0015_workcompensation_related_debts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdebtdetail',
            name='locked_for_compensation',
            field=models.BooleanField(default=False, help_text='Закреплено для отработки'),
        ),
        migrations.AlterField(
            model_name='workcompensation',
            name='related_debts',
            field=models.ManyToManyField(blank=True, help_text='Нарушения, покрываемые данной заявкой', related_name='compensations', to='hourly_locks.workdebtdetail'),
        ),
    ]
