# Generated by Django 5.2.6 on 2025-10-23 06:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0016_workdebtdetail_locked_for_compensation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCompensationDebtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('schedule', models.CharField(blank=True, max_length=20, null=True)),
                ('norm_full', models.DurationField(default=datetime.timedelta)),
                ('fact_full', models.DurationField(default=datetime.timedelta)),
                ('debt_full', models.DurationField(default=datetime.timedelta)),
                ('norm_lock', models.DurationField(default=datetime.timedelta)),
                ('fact_lock', models.DurationField(default=datetime.timedelta)),
                ('debt_lock', models.DurationField(default=datetime.timedelta)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_debts', to='hourly_locks.workcompensation', verbose_name='Заявка')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hourly_locks.operator')),
            ],
        ),
    ]
