# Generated by Django 5.2.6 on 2025-10-27 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0018_alter_workcompensation_related_debts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdebt',
            name='total_debt',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
