# Generated by Django 5.2.6 on 2025-10-28 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0019_alter_workdebt_total_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer_of_wh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('transfer', 'Перенос рабочего дня'), ('training', 'Обучения'), ('exception', 'Исключение')], default='transfer', max_length=30)),
                ('status', models.CharField(choices=[('completed', 'Завершён'), ('in process', 'В процессе'), ('declined', 'Отклонен'), ('pending', 'В ожидании'), ('partial', 'Частично')], default='pending', max_length=30)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('hour_from', models.TimeField(blank=True, null=True)),
                ('hour_to', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='pdfs_twh/')),
                ('screens', models.ImageField(blank=True, null=True, upload_to='screens_twh/')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixeds', to=settings.AUTH_USER_MODEL, verbose_name='Кем зафиксирован')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hourly_locks.operator')),
            ],
        ),
    ]
