# Generated by Django 5.2.6 on 2025-10-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0021_alter_transfer_of_wh_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_of_wh',
            name='type',
            field=models.CharField(choices=[('transfer', 'Перенос рабочего дня'), ('training', 'Обучения'), ('exception', 'Исключение'), ('office_work', 'Хозяйственные работы'), ('benefits', 'Льгота')], default='transfer', max_length=30),
        ),
    ]
