# Generated by Django 5.2.6 on 2025-11-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0022_alter_transfer_of_wh_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdebtdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='workcompensation',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Подтверждено'), ('partial', 'Частично'), ('declined', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
