# Generated by Django 5.2.6 on 2025-11-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0023_workdebtdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcompensation',
            name='related_debts',
            field=models.ManyToManyField(blank=True, help_text='Нарушения, выбранные для данной заявки', related_name='compensations', to='hourly_locks.workdebtdetail'),
        ),
    ]
