# Generated by Django 5.2.6 on 2025-11-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0024_alter_workcompensation_related_debts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcompensation',
            name='duration',
            field=models.DurationField(help_text='Сколько часов должен отработать / исключить'),
        ),
    ]
