# Generated by Django 5.2.6 on 2025-11-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0025_alter_workcompensation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcompensation',
            name='duration',
            field=models.DurationField(help_text='Сколько часов должен отработать'),
        ),
        migrations.AlterField(
            model_name='workcompensation',
            name='related_debts',
            field=models.ManyToManyField(blank=True, help_text='Нарушения, выбранные для данной заявки (переносятся в историю при сохранении)', related_name='compensations', to='hourly_locks.workdebtdetail'),
        ),
    ]
