# Generated by Django 5.2.6 on 2025-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0026_alter_workcompensation_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcompensation',
            name='type',
            field=models.CharField(choices=[('compensation', 'Отработка'), ('exception', 'Исключение'), ('partial_exception', 'Частичное исключение'), ('no_compensation', 'Не отработает')], default='compensation', help_text='Тип заявки:', max_length=20),
        ),
    ]
