# Generated by Django 5.2.6 on 2025-11-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0028_alter_workcompensation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcompensation',
            name='duration',
            field=models.DurationField(help_text='Сколько часов должен отработать'),
        ),
        migrations.AlterField(
            model_name='workcompensation',
            name='type',
            field=models.CharField(choices=[('compensation', 'Отработка'), ('exception', 'Исключение'), ('no_compensation', 'Не отработает')], default='compensation', help_text='Тип заявки:', max_length=20),
        ),
    ]
