# Generated by Django 5.2.6 on 2025-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0029_alter_workcompensation_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcompensation',
            name='duration',
            field=models.DurationField(help_text='Сколько часов должен отработать / исключить'),
        ),
        migrations.AlterField(
            model_name='workcompensation',
            name='related_debts',
            field=models.ManyToManyField(blank=True, help_text='Нарушения, выбранные для данной заявки (переносятся в историю при отработке/исключении)', related_name='compensations', to='hourly_locks.workdebtdetail'),
        ),
        migrations.AlterField(
            model_name='workcompensation',
            name='type',
            field=models.CharField(choices=[('compensation', 'Отработка'), ('exception', 'Исключение'), ('partial_exception', 'Частичное исключение'), ('no_compensation', 'Не отработает')], default='compensation', help_text='Тип заявки:', max_length=20),
        ),
    ]
