# Generated by Django 5.2.6 on 2025-12-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0030_alter_workcompensation_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_of_wh',
            name='type',
            field=models.CharField(choices=[('transfer', 'Перенос рабочего дня'), ('training', 'Обучение'), ('exception', 'Исключение'), ('office_work', 'Хозяйственные работы'), ('benefits', 'Льгота'), ('sl', 'БЛ'), ('wc', 'БС'), ('study', 'Учёба'), ('vacation', 'Отпуск')], default='transfer', max_length=30),
        ),
        migrations.AlterField(
            model_name='workcompensation',
            name='type',
            field=models.CharField(choices=[('compensation', 'Отработка'), ('exception', 'Исключение'), ('partial_exception', 'Частичное исключение'), ('no_compensation', 'Не отработает'), ('sl', 'БЛ'), ('wc', 'БС'), ('study', 'Учёба'), ('vacation', 'Отпуск'), ('nb_compensation', 'Отработать н/б')], default='compensation', help_text='Тип заявки:', max_length=20),
        ),
    ]
