# Generated by Django 5.2.6 on 2026-01-07 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0031_alter_transfer_of_wh_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_of_wh',
            name='fact_duration',
            field=models.DurationField(blank=True, help_text="Фактически выполнено при статусе 'Частично'", null=True),
        ),
        migrations.AddField(
            model_name='workcompensation',
            name='fact_duration',
            field=models.DurationField(blank=True, help_text="Фактически отработано при статусе 'Частично'", null=True),
        ),
        migrations.AddField(
            model_name='workdebt',
            name='total_debt_accumulated',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Суммарная задолженность, начисленная за всё время (не уменьшается)'),
        ),
    ]
