# Generated by Django 5.2.6 on 2026-01-17 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0032_transfer_of_wh_fact_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklogsdaily',
            name='aftercallduration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='worklogsdaily',
            name='busyduration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='worklogsdaily',
            name='fullduration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='worklogsdaily',
            name='holdduration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='worklogsdaily',
            name='idleduration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='worklogsdaily',
            name='lazyduration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='worklogsdaily',
            name='lockduration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='worklogsdaily',
            name='relaxduration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
