# Generated by Django 5.2.6 on 2026-02-24 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0033_alter_worklogsdaily_aftercallduration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='schedule',
            field=models.CharField(blank=True, db_index=True, help_text='Рабочий график сотрудника', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transfer_of_wh',
            name='type',
            field=models.CharField(choices=[('transfer', 'Перенос рабочего дня'), ('time_off', 'Отпрашивание'), ('training', 'Обучение'), ('exception', 'Исключение'), ('office_work', 'Хозяйственные работы'), ('benefits', 'Льгота'), ('sl', 'БЛ'), ('wc', 'БС'), ('study', 'Учёба'), ('vacation', 'Отпуск')], default='transfer', max_length=30),
        ),
        migrations.CreateModel(
            name='OperatorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('days', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_schedules', to='hourly_locks.operator')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'month'], name='hourly_lock_year_81c44c_idx')],
                'unique_together': {('operator', 'year', 'month')},
            },
        ),
    ]
