# Generated by Django 5.2.6 on 2026-02-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0034_operator_schedule_alter_transfer_of_wh_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcompensation',
            name='debts_for_user_view',
            field=models.JSONField(blank=True, help_text='Snapshot всех WDD на момент создания заявки', null=True),
        ),
    ]
