# Generated by Django 5.2.6 on 2026-04-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0035_workcompensation_debts_for_user_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='schedule',
            field=models.CharField(blank=True, db_index=True, help_text='Рабочий график сотрудника', max_length=250, null=True),
        ),
    ]
