# Generated by Django 5.2.6 on 2026-05-26 16:40

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hourly_locks', '0036_alter_operator_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('skip_debt_calc', 'Не считать долг'), ('skip_log_load', 'Не загружать лог'), ('manual_verification_only', 'Только ручная проверка'), ('freeze_total_debt', 'Заморозить общий долг'), ('skip_compensation_check', 'Не проверять компенсации автоматически'), ('skip_transfer_check', 'Не проверять переносы автоматически')], db_index=True, max_length=50, verbose_name='Тип переопределения')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, help_text='NULL = бессрочно', null=True, verbose_name='Действует до')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда деактивировано')),
            ],
            options={
                'verbose_name': 'Переопределение автоматики',
                'verbose_name_plural': 'Переопределения автоматики',
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('approved', 'Подтверждено'), ('partial', 'Частично'), ('declined', 'Отклонено'), ('completed', 'Завершено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='requests/pdf/', verbose_name='PDF файл')),
                ('screens', models.ImageField(blank=True, null=True, upload_to='requests/screens/', verbose_name='Скриншот')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('source', models.CharField(choices=[('requested', 'Запрошена заранее'), ('retroactive', 'Ретроактивная (по факту)'), ('system', 'Системная'), ('manual', 'Вручную (супервайзером)')], db_index=True, default='requested', max_length=20, verbose_name='Источник')),
                ('planned_date', models.DateField(db_index=True, help_text='Дата отработки (для retroactive — дата, когда оператор уже отработал)', verbose_name='Планируемая дата')),
                ('requested_duration', models.DurationField(verbose_name='Запрошенная длительность')),
                ('verified_duration', models.DurationField(blank=True, help_text='Фактически засчитанное время после проверки', null=True, verbose_name='Подтверждённая длительность')),
                ('remaining_debt', models.DurationField(blank=True, help_text='Невыполненная часть (в статусе partial)', null=True, verbose_name='Остаток долга')),
                ('deducted', models.BooleanField(default=False, help_text='Списано ли из WorkDebt.current_debt', verbose_name='Списано')),
                ('debts_snapshot', models.JSONField(blank=True, default=list, help_text='Снимок долгов на момент создания заявки', verbose_name='Снимок долгов')),
                ('claim_metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительный контекст для retroactive: свидетели, причина, почему оператор отработал без предварительной заявки и т.п.', verbose_name='Метаданные заявки')),
                ('auto_check_result', models.JSONField(blank=True, default=dict, help_text='Результат автоматической проверки: fact_full, fact_lock, shift_norm, available_overtime, computed_credit', verbose_name='Результат авто-проверки')),
                ('auto_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата авто-проверки')),
            ],
            options={
                'verbose_name': 'Компенсация',
                'verbose_name_plural': 'Компенсации',
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompensationDebtLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict, help_text='Полная копия записи долга на момент создания связи', verbose_name='Снимок долга')),
                ('applied', models.BooleanField(db_index=True, default=False, help_text='Списан ли долг по этой связи', verbose_name='Применено')),
                ('applied_amount', models.DurationField(blank=True, null=True, verbose_name='Списанная сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Связь компенсации с долгом',
                'verbose_name_plural': 'Связи компенсаций с долгами',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год окончания')),
                ('month', models.PositiveSmallIntegerField(help_text='Месяц, в котором цикл заканчивается (1-12)', verbose_name='Месяц окончания')),
                ('start_date', models.DateField(help_text='20-е число предыдущего месяца', verbose_name='Начало')),
                ('end_date', models.DateField(help_text='19-е число текущего месяца', verbose_name='Окончание')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('closing', 'Закрывается'), ('closed', 'Закрытый')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Открыт')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт')),
                ('archive_stats', models.JSONField(blank=True, default=dict, help_text='Сколько записей перенесено в архив', verbose_name='Статистика архивирования')),
            ],
            options={
                'verbose_name': 'Цикл',
                'verbose_name_plural': 'Циклы',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('log_loaded', 'Лог загружен'), ('log_load_failed', 'Ошибка загрузки лога'), ('debt_calculated', 'Долг рассчитан'), ('compensation_created', 'Компенсация создана'), ('compensation_verified', 'Компенсация проверена'), ('transfer_created', 'Заявка создана'), ('transfer_completed', 'Заявка завершена'), ('cycle_opened', 'Цикл открыт'), ('cycle_closing', 'Цикл закрывается'), ('cycle_closed', 'Цикл закрыт'), ('archived', 'Запись архивирована'), ('manual_adjustment', 'Ручная правка'), ('automation_override', 'Автоматика отключена'), ('api_error', 'Ошибка API'), ('sheets_synced', 'Sheets синхронизированы'), ('schedule_changed', 'Расписание изменено'), ('night_pipeline_run', 'Ночной конвейер запущен'), ('retroactive_check', 'Ретроактивная проверка')], db_index=True, max_length=50, verbose_name='Тип события')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], db_index=True, default='info', max_length=20, verbose_name='Уровень')),
                ('target_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип объекта')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Событие журнала',
                'verbose_name_plural': 'Журнал событий',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ManualAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('debt_detail', 'Запись долга (дневная)'), ('debt_total', 'Общий долг (WorkDebt)'), ('compensation', 'Компенсация'), ('transfer', 'Перенос/Отгул'), ('log_daily', 'Ежедневный лог'), ('schedule_day', 'День расписания')], db_index=True, max_length=30, verbose_name='Тип объекта')),
                ('target_id', models.PositiveIntegerField(db_index=True, verbose_name='ID объекта')),
                ('field_name', models.CharField(max_length=100, verbose_name='Поле')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.JSONField(verbose_name='Новое значение')),
                ('reason_code', models.CharField(choices=[('emergency', 'Чрезвычайная ситуация'), ('system_error', 'Системная ошибка'), ('management_decision', 'Решение руководства'), ('data_correction', 'Исправление данных'), ('policy_exception', 'Исключение из правил'), ('manual_verification', 'Ручная проверка'), ('other', 'Другое')], max_length=50, verbose_name='Код причины')),
                ('reason_text', models.TextField(help_text='Подробное описание — обязательно', verbose_name='Описание причины')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда правлено')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Требует подтверждения')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда подтверждено')),
            ],
            options={
                'verbose_name': 'Ручная правка',
                'verbose_name_plural': 'Ручные правки',
                'ordering': ['-adjusted_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('operator', 'Оператор'), ('debt_detail', 'Запись долга'), ('compensation', 'Компенсация'), ('transfer', 'Перенос/Отгул'), ('log_daily', 'Ежедневный лог'), ('schedule_day', 'День расписания'), ('cycle', 'Цикл')], db_index=True, max_length=30, verbose_name='Тип объекта')),
                ('target_id', models.PositiveIntegerField(db_index=True, verbose_name='ID объекта')),
                ('text', models.TextField(verbose_name='Текст')),
                ('visibility', models.CharField(choices=[('public', 'Все видят'), ('operator', 'Сам оператор'), ('supervisor', 'Супервайзер и выше'), ('manager_only', 'Только менеджер')], default='supervisor', max_length=20, verbose_name='Видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Примечание',
                'verbose_name_plural': 'Примечания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatorScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Выходной')),
                ('source', models.CharField(choices=[('sheets', 'Google Sheets'), ('manual', 'Вручную'), ('system', 'Системно')], default='sheets', max_length=20, verbose_name='Источник')),
                ('raw_value', models.CharField(blank=True, help_text='Оригинальное значение из Sheets (для аудита)', max_length=50, null=True, verbose_name='Исходное значение')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Синхронизирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'День расписания оператора',
                'verbose_name_plural': 'Расписание операторов (по дням)',
            },
        ),
        migrations.CreateModel(
            name='RequestTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('compensation', 'Компенсация'), ('transfer', 'Перенос / Отгул')], db_index=True, max_length=20, verbose_name='Категория')),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='Код')),
                ('display_name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('requires_date_from', models.BooleanField(default=False, verbose_name='Требует дату начала')),
                ('requires_date_to', models.BooleanField(default=False, verbose_name='Требует дату окончания')),
                ('requires_hour_range', models.BooleanField(default=False, verbose_name='Требует диапазон часов')),
                ('requires_duration', models.BooleanField(default=False, verbose_name='Требует длительность')),
                ('requires_related_debts', models.BooleanField(default=False, verbose_name='Требует выбор долгов')),
                ('creates_debt_if_unmet', models.BooleanField(default=True, help_text='Если оператор не выполнил — создаётся долг. Для vacation/sl — False.', verbose_name='Создаёт долг при невыполнении')),
                ('exempts_from_daily_debt', models.BooleanField(default=False, help_text='В этот день долг не считается (training, vacation, sl, wc, study).', verbose_name='Освобождает от ежедневного долга')),
                ('auto_approve_on_create', models.BooleanField(default=False, help_text='Сразу approved при создании (exception, no_compensation).', verbose_name='Авто-одобрение при создании')),
                ('allows_past_date', models.BooleanField(default=False, help_text='True для ретроактивных заявок.', verbose_name='Разрешает прошедшие даты')),
                ('requires_supervisor_approval', models.BooleanField(default=False, help_text='Даже после авто-проверки супервайзер должен подтвердить вручную.', verbose_name='Требует подтверждения супервайзера')),
                ('min_duration', models.DurationField(blank=True, null=True, verbose_name='Минимальная длительность')),
                ('max_duration', models.DurationField(blank=True, null=True, verbose_name='Максимальная длительность')),
                ('verification_strategy', models.CharField(choices=[('schedule_based', 'По расписанию (overtime - over_lock)'), ('net_based', 'По чистому времени (full - lock)'), ('day_off_based', 'По выходному (net = credit)'), ('date_range_based', 'По диапазону дат'), ('hour_range_based', 'По диапазону часов'), ('auto_approve', 'Автоматическое одобрение'), ('manual_only', 'Только вручную'), ('night_pipeline', 'Ночной конвейер 20-08'), ('retroactive_check', 'Ретроактивная проверка (по факту)')], default='schedule_based', max_length=50, verbose_name='Стратегия проверки')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Правило типа заявки',
                'verbose_name_plural': 'Правила типов заявок',
                'ordering': ['category', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Например: '08-20', '20-08', '11-20'", max_length=20, unique=True, verbose_name='Код')),
                ('display_name', models.CharField(max_length=100, verbose_name='Название')),
                ('start_time', models.TimeField(verbose_name='Начало смены')),
                ('end_time', models.TimeField(verbose_name='Окончание смены')),
                ('crosses_midnight', models.BooleanField(default=False, help_text='Ночная смена, переходящая через полночь', verbose_name='Через полночь')),
                ('norm_full', models.DurationField(help_text='Например: 12:00 / 9:00 / 8:00', verbose_name='Норма рабочего времени')),
                ('norm_lock_soft_cap', models.DurationField(help_text='Например: 2:20 или 1:46', verbose_name='Норма перерыва (мягкая)')),
                ('norm_lock_warn_at', models.DurationField(default=datetime.timedelta(0), help_text='Например: 1:30 для 9-часовой смены. 0 = не используется.', verbose_name='Порог штрафа за перерыв')),
                ('tolerance_undertime', models.DurationField(default=datetime.timedelta(0), help_text='Например: 10 минут — недоработка в пределах допуска не создаёт долг', verbose_name='Допуск недоработки')),
                ('fetch_hour_padding', models.PositiveSmallIntegerField(default=1, help_text='На сколько часов расширять окно при загрузке логов с API', verbose_name='Расширение часов при загрузке')),
                ('is_night', models.BooleanField(default=False, verbose_name='Ночная')),
                ('requires_special_pipeline', models.BooleanField(default=False, help_text='True для смены 20-08 (специальный ночной конвейер)', verbose_name='Требует спец. конвейера')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Ключ')),
                ('value', models.JSONField(verbose_name='Значение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('valid_from', models.DateField(default=datetime.date.today, verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Системная политика',
                'verbose_name_plural': 'Системные политики',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('approved', 'Подтверждено'), ('partial', 'Частично'), ('declined', 'Отклонено'), ('completed', 'Завершено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='requests/pdf/', verbose_name='PDF файл')),
                ('screens', models.ImageField(blank=True, null=True, upload_to='requests/screens/', verbose_name='Скриншот')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('date_from', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата начала')),
                ('date_to', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата окончания')),
                ('hour_from', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('hour_to', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('requested_duration', models.DurationField(blank=True, null=True, verbose_name='Запрошенная длительность')),
                ('verified_duration', models.DurationField(blank=True, null=True, verbose_name='Подтверждённая длительность')),
                ('remaining_debt', models.DurationField(blank=True, null=True, verbose_name='Остаток долга')),
            ],
            options={
                'verbose_name': 'Заявка (перенос/отгул)',
                'verbose_name_plural': 'Заявки (переносы/отгулы)',
                'ordering': ['-date_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLogDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День')),
                ('shift_code_snapshot', models.CharField(blank=True, help_text='Код смены сохраняется даже после удаления Shift', max_length=20, null=True, verbose_name='Код смены (снимок)')),
                ('start_at', models.DateTimeField(blank=True, help_text='Точное время начала смены (для ночных смен)', null=True, verbose_name='Фактическое начало')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое окончание')),
                ('aftercall_duration', models.DurationField(default=datetime.timedelta, verbose_name='После звонка')),
                ('busy_duration', models.DurationField(default=datetime.timedelta, verbose_name='Занято (разговор)')),
                ('hold_duration', models.DurationField(default=datetime.timedelta, verbose_name='Удержание')),
                ('idle_duration', models.DurationField(default=datetime.timedelta, verbose_name='Простой')),
                ('lazy_duration', models.DurationField(default=datetime.timedelta, verbose_name='Без активности')),
                ('lock_duration', models.DurationField(default=datetime.timedelta, verbose_name='Перерыв (lock)')),
                ('relax_duration', models.DurationField(default=datetime.timedelta, verbose_name='Отдых')),
                ('full_duration', models.DurationField(default=datetime.timedelta, verbose_name='Общее время')),
                ('is_special_aggregation', models.BooleanField(default=False, help_text='True для агрегации 20-08 + компенсация', verbose_name='Спец. агрегация')),
                ('loaded_at', models.DateTimeField(auto_now=True, verbose_name='Загружен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Ежедневный лог',
                'verbose_name_plural': 'Ежедневные логи',
            },
        ),
        migrations.AlterUniqueTogether(
            name='operatorschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='operatorschedule',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='transfer_of_wh',
            name='fixed_by',
        ),
        migrations.RemoveField(
            model_name='transfer_of_wh',
            name='operator',
        ),
        migrations.AlterUniqueTogether(
            name='transferedworkday',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='transferedworkday',
            name='fixed_by',
        ),
        migrations.RemoveField(
            model_name='transferedworkday',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='workcompensation',
            name='fixed_by',
        ),
        migrations.RemoveField(
            model_name='workcompensation',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='workcompensation',
            name='related_debts',
        ),
        migrations.RemoveField(
            model_name='workcompensationdebtrecord',
            name='compensation',
        ),
        migrations.RemoveField(
            model_name='workcompensationdebtrecord',
            name='operator',
        ),
        migrations.AlterUniqueTogether(
            name='worklogsdaily',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='worklogsdaily',
            name='operator',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа операторов', 'verbose_name_plural': 'Группы операторов'},
        ),
        migrations.AlterModelOptions(
            name='logos',
            options={'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотипы'},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Оператор', 'verbose_name_plural': 'Операторы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='workdebt',
            options={'verbose_name': 'Долг оператора', 'verbose_name_plural': 'Долги операторов'},
        ),
        migrations.AlterModelOptions(
            name='workdebtdetail',
            options={'verbose_name': 'Детализация долга', 'verbose_name_plural': 'Детализация долгов'},
        ),
        migrations.RemoveIndex(
            model_name='operator',
            name='hourly_lock_role_4d00ff_idx',
        ),
        migrations.RemoveField(
            model_name='group',
            name='supervisors',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='role',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='workdebtdetail',
            name='schedule',
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='group',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_groups', to=settings.AUTH_USER_MODEL, verbose_name='Супервайзер'),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AddField(
            model_name='operator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operator',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Для уволенных сотрудников — False', verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='operator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AddField(
            model_name='workdebt',
            name='current_debt',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Текущий долг'),
        ),
        migrations.AddField(
            model_name='workdebt',
            name='total_accumulated',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Сумма всех начисленных долгов в цикле (не уменьшается)', verbose_name='Накопленный долг'),
        ),
        migrations.AddField(
            model_name='workdebt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AddField(
            model_name='workdebtdetail',
            name='make_up_wh',
            field=models.DurationField(default=datetime.timedelta, help_text='Переработка, компенсирующая превышение перерыва', verbose_name='Компенсирующая переработка'),
        ),
        migrations.AddField(
            model_name='workdebtdetail',
            name='shift_code_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код смены (снимок)'),
        ),
        migrations.AddField(
            model_name='workdebtdetail',
            name='source',
            field=models.CharField(choices=[('shift', 'Смена'), ('transfer', 'Перенос'), ('time_off', 'Отпрашивание'), ('compensation_shortfall', 'Недоработанная компенсация'), ('nb_compensation_shortfall', 'Недоработанная NB-компенсация'), ('manual', 'Вручную добавлен')], db_index=True, default='shift', max_length=30, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='workdebtdetail',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID связанной Compensation/Transfer', null=True, verbose_name='ID исходной заявки'),
        ),
        migrations.AddField(
            model_name='workdebtdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AddField(
            model_name='workdebtdetail',
            name='violation_type',
            field=models.CharField(blank=True, choices=[('insufficient_wh', 'Недоработка'), ('exceeding_break', 'Превышение перерыва'), ('both_violations', 'Оба нарушения')], db_index=True, max_length=30, null=True, verbose_name='Тип нарушения'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='hourly_locks.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='login_id',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='operators/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='surname',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='operator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='hourly_locks.operator', verbose_name='Связанный оператор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Оператор'), ('supervisor', 'Супервайзер'), ('manager', 'Менеджер'), ('admin', 'Администратор')], db_index=True, default='operator', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='workdebt',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='hourly_locks.operator', verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='day',
            field=models.DateField(db_index=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='debt_full',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Долг (полный)'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='debt_lock',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Долг по перерыву'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='fact_full',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Факт (полный)'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='fact_lock',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Факт перерыва'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='locked_for_compensation',
            field=models.BooleanField(db_index=True, default=False, help_text='Привязан к заявке — повторно списать нельзя', verbose_name='Привязан к компенсации'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='norm_full',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Норма (полная)'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='norm_lock',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Норма перерыва'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_details', to='hourly_locks.operator', verbose_name='Оператор'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['is_active'], name='hourly_lock_is_acti_f57596_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='hourly_lock_role_35db39_idx'),
        ),
        migrations.AddField(
            model_name='automationoverride',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides_created', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AddField(
            model_name='automationoverride',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_deactivated', to=settings.AUTH_USER_MODEL, verbose_name='Кем деактивировано'),
        ),
        migrations.AddField(
            model_name='automationoverride',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_overrides', to='hourly_locks.operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем зафиксировано'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hourly_locks.operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем проверено'),
        ),
        migrations.AddField(
            model_name='compensationdebtlink',
            name='compensation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_links', to='hourly_locks.compensation', verbose_name='Компенсация'),
        ),
        migrations.AddField(
            model_name='compensationdebtlink',
            name='debt_detail',
            field=models.ForeignKey(blank=True, help_text='Если NULL — запись долга удалена, читайте snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_links', to='hourly_locks.workdebtdetail', verbose_name='Запись долга'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Кем закрыт'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
        migrations.AddField(
            model_name='workdebt',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
        migrations.AddField(
            model_name='workdebtdetail',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_details', to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
        migrations.AlterUniqueTogether(
            name='workdebt',
            unique_together={('operator', 'cycle')},
        ),
        migrations.AddIndex(
            model_name='workdebt',
            index=models.Index(fields=['operator'], name='hourly_lock_operato_318912_idx'),
        ),
        migrations.AddIndex(
            model_name='workdebt',
            index=models.Index(fields=['operator', 'cycle'], name='hourly_lock_operato_dcb370_idx'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hourly_locks.operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AddField(
            model_name='manualadjustment',
            name='adjusted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_made', to=settings.AUTH_USER_MODEL, verbose_name='Кем правлено'),
        ),
        migrations.AddField(
            model_name='manualadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_approved', to=settings.AUTH_USER_MODEL, verbose_name='Кем подтверждено'),
        ),
        migrations.AddField(
            model_name='manualadjustment',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Денормализация — для быстрого поиска по оператору', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='hourly_locks.operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='operatorscheduleday',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='hourly_locks.operator', verbose_name='Оператор'),
        ),
        migrations.AddIndex(
            model_name='requesttyperule',
            index=models.Index(fields=['category', 'is_active'], name='hourly_lock_categor_f2144c_idx'),
        ),
        migrations.AddIndex(
            model_name='requesttyperule',
            index=models.Index(fields=['code'], name='hourly_lock_code_9fb702_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requesttyperule',
            unique_together={('category', 'code')},
        ),
        migrations.AddField(
            model_name='compensation',
            name='type_rule',
            field=models.ForeignKey(limit_choices_to={'category': 'compensation'}, on_delete=django.db.models.deletion.PROTECT, related_name='compensations', to='hourly_locks.requesttyperule', verbose_name='Тип заявки'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['is_active'], name='hourly_lock_is_acti_844a03_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['code', 'is_active'], name='hourly_lock_code_227f1d_idx'),
        ),
        migrations.AddField(
            model_name='operatorscheduleday',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Пустое значение = выходной день', null=True, on_delete=django.db.models.deletion.PROTECT, to='hourly_locks.shift', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='workdebtdetail',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hourly_locks.shift', verbose_name='Смена'),
        ),
        migrations.AddIndex(
            model_name='workdebtdetail',
            index=models.Index(fields=['operator', 'day'], name='hourly_lock_operato_ce817b_idx'),
        ),
        migrations.AddIndex(
            model_name='workdebtdetail',
            index=models.Index(fields=['cycle'], name='hourly_lock_cycle_i_bffccc_idx'),
        ),
        migrations.AddIndex(
            model_name='workdebtdetail',
            index=models.Index(fields=['operator', 'cycle'], name='hourly_lock_operato_c8ce7a_idx'),
        ),
        migrations.AddIndex(
            model_name='workdebtdetail',
            index=models.Index(fields=['source'], name='hourly_lock_source_c95444_idx'),
        ),
        migrations.AddIndex(
            model_name='workdebtdetail',
            index=models.Index(fields=['locked_for_compensation'], name='hourly_lock_locked__fac806_idx'),
        ),
        migrations.AddField(
            model_name='systempolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем зафиксировано'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hourly_locks.operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='type_rule',
            field=models.ForeignKey(limit_choices_to={'category': 'transfer'}, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='hourly_locks.requesttyperule', verbose_name='Тип заявки'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем проверено'),
        ),
        migrations.AddField(
            model_name='worklogdaily',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
        migrations.AddField(
            model_name='worklogdaily',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='hourly_locks.operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='worklogdaily',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Смена на момент записи лога', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hourly_locks.shift', verbose_name='Смена'),
        ),
        migrations.DeleteModel(
            name='OperatorSchedule',
        ),
        migrations.DeleteModel(
            name='Transfer_of_wh',
        ),
        migrations.DeleteModel(
            name='TransferedWorkDay',
        ),
        migrations.DeleteModel(
            name='WorkCompensation',
        ),
        migrations.DeleteModel(
            name='WorkCompensationDebtRecord',
        ),
        migrations.DeleteModel(
            name='WorkLogsDaily',
        ),
        migrations.AddIndex(
            model_name='automationoverride',
            index=models.Index(fields=['operator', 'is_active'], name='hourly_lock_operato_113c75_idx'),
        ),
        migrations.AddIndex(
            model_name='automationoverride',
            index=models.Index(fields=['override_type', 'is_active'], name='hourly_lock_overrid_f32f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='automationoverride',
            index=models.Index(fields=['valid_from', 'valid_to'], name='hourly_lock_valid_f_bc8bde_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationdebtlink',
            index=models.Index(fields=['compensation'], name='hourly_lock_compens_6aedda_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationdebtlink',
            index=models.Index(fields=['debt_detail'], name='hourly_lock_debt_de_07196a_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationdebtlink',
            index=models.Index(fields=['applied'], name='hourly_lock_applied_867b06_idx'),
        ),
        migrations.AddConstraint(
            model_name='compensationdebtlink',
            constraint=models.UniqueConstraint(condition=models.Q(('applied', True)), fields=('debt_detail',), name='unique_applied_debt_link'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['status'], name='hourly_lock_status_dfff2d_idx'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['year', 'month'], name='hourly_lock_year_d49bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['start_date', 'end_date'], name='hourly_lock_start_d_bec5aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('year', 'month')},
        ),
        migrations.RemoveField(
            model_name='workdebt',
            name='total_debt',
        ),
        migrations.RemoveField(
            model_name='workdebt',
            name='total_debt_accumulated',
        ),
        migrations.RemoveField(
            model_name='workdebt',
            name='total_debt_day',
        ),
        migrations.RemoveField(
            model_name='workdebt',
            name='total_debt_hour',
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='hourly_lock_event_t_617136_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['operator', 'timestamp'], name='hourly_lock_operato_07bfd4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['level'], name='hourly_lock_level_d66330_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['target_type', 'target_id'], name='hourly_lock_target__30ac33_idx'),
        ),
        migrations.AddIndex(
            model_name='manualadjustment',
            index=models.Index(fields=['target_type', 'target_id'], name='hourly_lock_target__6d13e5_idx'),
        ),
        migrations.AddIndex(
            model_name='manualadjustment',
            index=models.Index(fields=['operator'], name='hourly_lock_operato_1f0679_idx'),
        ),
        migrations.AddIndex(
            model_name='manualadjustment',
            index=models.Index(fields=['adjusted_at'], name='hourly_lock_adjuste_30b0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='manualadjustment',
            index=models.Index(fields=['adjusted_by'], name='hourly_lock_adjuste_fa217d_idx'),
        ),
        migrations.AddIndex(
            model_name='manualadjustment',
            index=models.Index(fields=['reason_code'], name='hourly_lock_reason__d74cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['target_type', 'target_id'], name='hourly_lock_target__cf38e7_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='hourly_lock_created_0bd302_idx'),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['operator', 'planned_date'], name='hourly_lock_operato_b1137a_idx'),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['status'], name='hourly_lock_status_c9de29_idx'),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['cycle', 'status'], name='hourly_lock_cycle_i_b89b24_idx'),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['planned_date', 'status'], name='hourly_lock_planned_f84f98_idx'),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['deducted'], name='hourly_lock_deducte_33dbca_idx'),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['source'], name='hourly_lock_source_770a07_idx'),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['source', 'status'], name='hourly_lock_source_dc76fb_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorscheduleday',
            index=models.Index(fields=['day'], name='hourly_lock_day_c5b1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorscheduleday',
            index=models.Index(fields=['operator', 'day'], name='hourly_lock_operato_0c88ad_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorscheduleday',
            index=models.Index(fields=['day', 'is_day_off'], name='hourly_lock_day_78b7aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorscheduleday',
            unique_together={('operator', 'day')},
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['operator', 'date_from'], name='hourly_lock_operato_9e901d_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['operator', 'date_to'], name='hourly_lock_operato_4b1cad_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['date_from', 'date_to'], name='hourly_lock_date_fr_123435_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='hourly_lock_status_1ae7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['cycle', 'status'], name='hourly_lock_cycle_i_df8fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['type_rule', 'status'], name='hourly_lock_type_ru_6dc4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogdaily',
            index=models.Index(fields=['day'], name='hourly_lock_day_b02874_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogdaily',
            index=models.Index(fields=['operator', 'day'], name='hourly_lock_operato_3c6641_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogdaily',
            index=models.Index(fields=['cycle'], name='hourly_lock_cycle_i_9a3f29_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogdaily',
            index=models.Index(fields=['operator', 'cycle'], name='hourly_lock_operato_c38831_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='worklogdaily',
            unique_together={('operator', 'day')},
        ),
    ]
