# Generated by Django 5.2.6 on 2026-05-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0037_automationoverride_compensation_compensationdebtlink_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compensationdebtlink',
            name='unique_applied_debt_link',
        ),
        migrations.AlterField(
            model_name='compensation',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
        migrations.AlterField(
            model_name='workdebt',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_details', to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
        migrations.AlterField(
            model_name='worklogdaily',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to='hourly_locks.cycle', verbose_name='Цикл'),
        ),
    ]
