# Generated by Django 5.2.6 on 2026-06-05 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0038_remove_compensationdebtlink_unique_applied_debt_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logos',
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.RemoveIndex(
            model_name='eventlog',
            name='hourly_lock_event_t_617136_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventlog',
            name='hourly_lock_level_d66330_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventlog',
            name='hourly_lock_target__30ac33_idx',
        ),
        migrations.AddField(
            model_name='requesttyperule',
            name='forbidden_on_day_off',
            field=models.BooleanField(default=False, help_text='True — заявку нельзя создать, если date_from или date_to приходится на выходной оператора (без смены).', verbose_name='Запрещён в выходной'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_events', to=settings.AUTH_USER_MODEL, verbose_name='Триггер'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_type', 'level'], name='hourly_lock_event_t_f526e7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['cycle', 'level'], name='hourly_lock_cycle_i_bd271c_idx'),
        ),
    ]
