# Generated by Django 5.2.6 on 2026-06-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0039_delete_logos_alter_eventlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Correlation ID (WFM sync)'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Correlation ID (WFM sync)'),
        ),
    ]
