# Generated by Django 5.2.6 on 2026-06-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0040_compensation_correlation_id_transfer_correlation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='photo',
        ),
    ]
