# Generated by Django 5.2.6 on 2026-06-23 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0042_seed_request_type_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День отработки')),
                ('allocated_duration', models.DurationField(help_text='Доля requested_duration, распределённая на этот день', verbose_name='Норма отработки на день')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Подтверждено'), ('partial', 'Частично'), ('declined', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус дня')),
                ('credited_duration', models.DurationField(blank=True, help_text='Фактически засчитанное время после проверки (Фаза 2)', null=True, verbose_name='Засчитано за день')),
                ('fact_full', models.DurationField(blank=True, null=True, verbose_name='Факт (работа)')),
                ('fact_lock', models.DurationField(blank=True, null=True, verbose_name='Факт (перерыв)')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('compensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='hourly_locks.compensation', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'День отработки',
                'verbose_name_plural': 'Дни отработки',
                'ordering': ['day'],
                'indexes': [models.Index(fields=['day'], name='hourly_lock_day_fc5533_idx'), models.Index(fields=['status'], name='hourly_lock_status_0a658a_idx'), models.Index(fields=['compensation', 'day'], name='hourly_lock_compens_3fd973_idx')],
                'unique_together': {('compensation', 'day')},
            },
        ),
    ]
