# Generated by Django 5.2.6 on 2026-06-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0044_remove_transfer_otrabotka'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='lock_part',
            field=models.DurationField(blank=True, help_text='isklyuchenie/obuchenie: сколько добавляется к допустимому перерыву', null=True, verbose_name='Доля в перерыв (lock)'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='wh_part',
            field=models.DurationField(blank=True, help_text='isklyuchenie/obuchenie: сколько уменьшает рабочую норму', null=True, verbose_name='Доля в рабочие часы (wh)'),
        ),
        migrations.AlterField(
            model_name='workdebtdetail',
            name='source',
            field=models.CharField(choices=[('shift', 'Смена'), ('transfer', 'Перенос'), ('time_off', 'Отпрашивание'), ('compensation_shortfall', 'Недоработанная компенсация'), ('nb_compensation_shortfall', 'Недоработанная NB-компенсация'), ('otrabotka_partial', 'Остаток частичной отработки'), ('manual', 'Вручную добавлен')], db_index=True, default='shift', max_length=30, verbose_name='Источник'),
        ),
    ]
