# Generated by Django 5.2.6 on 2026-06-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0046_alter_workdebtdetail_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdebtdetail',
            name='source',
            field=models.CharField(choices=[('shift', 'Смена'), ('transfer', 'Перенос'), ('time_off', 'Отпрашивание'), ('compensation_shortfall', 'Недоработанная компенсация'), ('nb_compensation_shortfall', 'Недоработанная NB-компенсация'), ('otrabotka_partial', 'Остаток частичной отработки'), ('otrabotka_violation', 'Нарушение при отработке (норма/перерыв/перебор)'), ('compensation_remainder', 'Остаток после частичного списания компенсацией'), ('manual', 'Вручную добавлен')], db_index=True, default='shift', max_length=30, verbose_name='Источник'),
        ),
    ]
