# Generated by Django 5.2.6 on 2026-06-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0048_remove_transfer_ne_otrabotaet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='repayment_compensation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otprashivanie_source', to='hourly_locks.compensation', verbose_name='План отработки (для отпрашивания)'),
        ),
        migrations.CreateModel(
            name='OtprashivanieDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День отпрашивания')),
                ('hour_from', models.TimeField(verbose_name='С (время)')),
                ('hour_to', models.TimeField(verbose_name='По (время)')),
                ('duration', models.DurationField(verbose_name='Длительность за день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otprashivanie_days', to='hourly_locks.transfer', verbose_name='Заявка отпрашивания')),
            ],
            options={
                'verbose_name': 'День отпрашивания',
                'verbose_name_plural': 'Дни отпрашивания',
                'ordering': ['day'],
                'indexes': [models.Index(fields=['day'], name='hourly_lock_day_ad290a_idx')],
                'unique_together': {('transfer', 'day')},
            },
        ),
    ]
