# Generated by Django 5.2.6 on 2026-06-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0049_transfer_repayment_compensation_otprashivanieday'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='subtype',
            field=models.CharField(blank=True, help_text='Напр. для «Прочие льготы»: otgul (отгул) / korotkiy_den (короткий день)', max_length=30, null=True, verbose_name='Подтип'),
        ),
    ]
