# Generated by Django 5.2.6 on 2026-06-29 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0050_transfer_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День')),
                ('hour_from', models.TimeField(blank=True, null=True, verbose_name='С (время)')),
                ('hour_to', models.TimeField(blank=True, null=True, verbose_name='По (время)')),
                ('duration', models.DurationField(blank=True, help_text='NULL = весь день; иначе уменьшение нормы на эту длительность', null=True, verbose_name='Длительность за день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_days', to='hourly_locks.transfer', verbose_name='Заявка-льгота')),
            ],
            options={
                'verbose_name': 'День льготы',
                'verbose_name_plural': 'Дни льготы',
                'ordering': ['day'],
                'indexes': [models.Index(fields=['day'], name='hourly_lock_day_8ed9c4_idx')],
                'unique_together': {('transfer', 'day')},
            },
        ),
    ]
