# Generated by Django 5.2.6 on 2026-06-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_locks', '0052_ucheba_rabochee_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdebtdetail',
            name='source',
            field=models.CharField(choices=[('shift', 'Смена'), ('transfer', 'Перенос'), ('time_off', 'Отпрашивание'), ('compensation_shortfall', 'Недоработанная компенсация'), ('nb_compensation_shortfall', 'Недоработанная NB-компенсация'), ('otrabotka_partial', 'Остаток частичной отработки'), ('otrabotka_violation', 'Нарушение при отработке (норма/перерыв/перебор)'), ('compensation_remainder', 'Остаток после частичного списания компенсацией'), ('ucheba', 'Недоработка в день учёбы в рабочее время'), ('manual', 'Вручную добавлен')], db_index=True, default='shift', max_length=30, verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='UchebaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День')),
                ('hour_from', models.TimeField(blank=True, null=True, verbose_name='С (план)')),
                ('hour_to', models.TimeField(blank=True, null=True, verbose_name='По (план)')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность учёбы (план)')),
                ('fact_full', models.DurationField(blank=True, null=True, verbose_name='Факт (полный)')),
                ('fact_lock', models.DurationField(blank=True, null=True, verbose_name='Факт (перерыв)')),
                ('debt', models.DurationField(blank=True, null=True, verbose_name='Долг дня')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Подтверждено'), ('partial', 'Частично'), ('declined', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucheba_days', to='hourly_locks.transfer', verbose_name='Заявка учёбы')),
            ],
            options={
                'verbose_name': 'День учёбы',
                'verbose_name_plural': 'Дни учёбы',
                'ordering': ['day'],
                'indexes': [models.Index(fields=['day'], name='hourly_lock_day_14353a_idx'), models.Index(fields=['status'], name='hourly_lock_status_7eaee2_idx')],
                'unique_together': {('transfer', 'day')},
            },
        ),
    ]
