# Generated by Django 5.2.6 on 2026-01-17 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveGroupSupervisorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField(db_index=True)),
                ('archive_month', models.PositiveSmallIntegerField(db_index=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.IntegerField(db_index=True)),
                ('group_name', models.CharField(db_index=True, max_length=100)),
                ('supervisor_id', models.IntegerField(db_index=True)),
                ('supervisor_login', models.CharField(db_index=True, max_length=50)),
                ('supervisor_fio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'archive_group_supervisor_map',
                'indexes': [models.Index(fields=['archive_year', 'archive_month'], name='archive_gro_archive_51301d_idx'), models.Index(fields=['supervisor_login'], name='archive_gro_supervi_034c20_idx'), models.Index(fields=['group_name'], name='archive_gro_group_n_1827f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArchiveTransferOfWh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField(db_index=True)),
                ('archive_month', models.PositiveSmallIntegerField(db_index=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('operator_id', models.IntegerField(db_index=True)),
                ('operator_login', models.CharField(db_index=True, max_length=50)),
                ('operator_fio', models.CharField(max_length=255)),
                ('group_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('group_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('hour_from', models.TimeField(blank=True, null=True)),
                ('hour_to', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('fact_duration', models.DurationField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('screens_path', models.CharField(blank=True, max_length=500, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('fixed_by_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archive_transfer_of_wh',
                'indexes': [models.Index(fields=['archive_year', 'archive_month'], name='archive_tra_archive_d7cad2_idx'), models.Index(fields=['operator_id'], name='archive_tra_operato_12d212_idx'), models.Index(fields=['group_name'], name='archive_tra_group_n_d31296_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArchiveWorkCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField(db_index=True)),
                ('archive_month', models.PositiveSmallIntegerField(db_index=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('operator_id', models.IntegerField(db_index=True)),
                ('operator_login', models.CharField(db_index=True, max_length=50)),
                ('operator_fio', models.CharField(max_length=255)),
                ('group_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('group_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('planned_date', models.DateField()),
                ('duration', models.DurationField()),
                ('fact_duration', models.DurationField(blank=True, null=True)),
                ('type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('deducted', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pdf_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('screens_path', models.CharField(blank=True, max_length=500, null=True)),
                ('fixed_by_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archive_work_compensation',
                'indexes': [models.Index(fields=['archive_year', 'archive_month'], name='archive_wor_archive_0cd14b_idx'), models.Index(fields=['operator_id', 'planned_date'], name='archive_wor_operato_079696_idx'), models.Index(fields=['group_name'], name='archive_wor_group_n_53fac4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArchiveWorkDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField(db_index=True)),
                ('archive_month', models.PositiveSmallIntegerField(db_index=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('operator_id', models.IntegerField(db_index=True)),
                ('operator_login', models.CharField(db_index=True, max_length=50)),
                ('operator_fio', models.CharField(max_length=255)),
                ('group_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('group_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('total_debt', models.DurationField(default=datetime.timedelta)),
                ('total_debt_accumulated', models.DurationField(default=datetime.timedelta)),
                ('total_debt_day', models.IntegerField()),
                ('total_debt_hour', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'archive_work_debt',
                'indexes': [models.Index(fields=['archive_year', 'archive_month'], name='archive_wor_archive_843e62_idx'), models.Index(fields=['operator_id'], name='archive_wor_operato_6677a4_idx'), models.Index(fields=['group_name'], name='archive_wor_group_n_72ea6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArchiveWorkDebtDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField(db_index=True)),
                ('archive_month', models.PositiveSmallIntegerField(db_index=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('operator_id', models.IntegerField(db_index=True)),
                ('operator_login', models.CharField(db_index=True, max_length=50)),
                ('operator_fio', models.CharField(max_length=255)),
                ('group_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('group_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('day', models.DateField(db_index=True)),
                ('schedule', models.CharField(blank=True, max_length=20, null=True)),
                ('norm_full', models.DurationField(default=datetime.timedelta)),
                ('fact_full', models.DurationField(default=datetime.timedelta)),
                ('debt_full', models.DurationField(default=datetime.timedelta)),
                ('norm_lock', models.DurationField(default=datetime.timedelta)),
                ('fact_lock', models.DurationField(default=datetime.timedelta)),
                ('debt_lock', models.DurationField(default=datetime.timedelta)),
                ('note', models.TextField(blank=True, null=True)),
                ('locked_for_compensation', models.BooleanField(default=False)),
                ('original_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archive_work_debt_detail',
                'indexes': [models.Index(fields=['archive_year', 'archive_month'], name='archive_wor_archive_a39d06_idx'), models.Index(fields=['operator_id', 'day'], name='archive_wor_operato_38e360_idx'), models.Index(fields=['group_name'], name='archive_wor_group_n_34ceae_idx')],
            },
        ),
    ]
