# Generated by Django 5.2.6 on 2026-05-29 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField()),
                ('archive_month', models.PositiveSmallIntegerField()),
                ('operator_id', models.PositiveIntegerField()),
                ('operator_login', models.CharField(max_length=50)),
                ('operator_fio', models.CharField(max_length=400)),
                ('group_id', models.PositiveIntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type_code', models.CharField(max_length=30)),
                ('type_display', models.CharField(max_length=100)),
                ('source', models.CharField(default='requested', help_text='requested / retroactive / system / manual', max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('planned_date', models.DateField()),
                ('requested_duration', models.DurationField()),
                ('verified_duration', models.DurationField(blank=True, null=True)),
                ('remaining_debt', models.DurationField(blank=True, null=True)),
                ('deducted', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('debts_snapshot', models.JSONField(blank=True, default=list)),
                ('debt_links_snapshot', models.JSONField(blank=True, default=list, help_text='CompensationDebtLink yozuvlarining nusxasi')),
                ('claim_metadata', models.JSONField(blank=True, default=dict)),
                ('auto_check_result', models.JSONField(blank=True, default=dict)),
                ('auto_check_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('screens_path', models.CharField(blank=True, max_length=500, null=True)),
                ('original_id', models.PositiveIntegerField(help_text='Asosiy DB dagi Compensation.id')),
                ('original_created_at', models.DateTimeField()),
                ('original_updated_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fixed_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('closed_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('closed_by_username', models.CharField(blank=True, max_length=150, null=True)),
                ('archive_stats', models.JSONField(blank=True, default=dict)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField()),
                ('archive_month', models.PositiveSmallIntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('operator_id', models.PositiveIntegerField(blank=True, null=True)),
                ('operator_login', models.CharField(blank=True, max_length=50, null=True)),
                ('target_type', models.CharField(blank=True, max_length=30, null=True)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('original_timestamp', models.DateTimeField()),
                ('triggered_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveManualAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField()),
                ('archive_month', models.PositiveSmallIntegerField()),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.PositiveIntegerField()),
                ('operator_id', models.PositiveIntegerField(blank=True, null=True)),
                ('operator_login', models.CharField(blank=True, max_length=50, null=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField()),
                ('reason_code', models.CharField(max_length=50)),
                ('reason_text', models.TextField()),
                ('adjusted_by_id', models.PositiveIntegerField()),
                ('adjusted_by_username', models.CharField(max_length=150)),
                ('adjusted_at', models.DateTimeField()),
                ('approved_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('original_id', models.PositiveIntegerField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveOperatorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField()),
                ('archive_month', models.PositiveSmallIntegerField()),
                ('operator_id', models.PositiveIntegerField()),
                ('operator_login', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('group_id', models.PositiveIntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField()),
                ('archive_month', models.PositiveSmallIntegerField()),
                ('operator_id', models.PositiveIntegerField()),
                ('operator_login', models.CharField(max_length=50)),
                ('operator_fio', models.CharField(max_length=400)),
                ('group_id', models.PositiveIntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type_code', models.CharField(max_length=30)),
                ('type_display', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('hour_from', models.TimeField(blank=True, null=True)),
                ('hour_to', models.TimeField(blank=True, null=True)),
                ('requested_duration', models.DurationField(blank=True, null=True)),
                ('verified_duration', models.DurationField(blank=True, null=True)),
                ('remaining_debt', models.DurationField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('screens_path', models.CharField(blank=True, max_length=500, null=True)),
                ('original_id', models.PositiveIntegerField()),
                ('original_created_at', models.DateTimeField()),
                ('original_updated_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fixed_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('was_split', models.BooleanField(default=False, help_text="Cross-cycle transfer'ning bo'lagi (bu tsikldagi qism)")),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveWorkLogDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_year', models.PositiveSmallIntegerField()),
                ('archive_month', models.PositiveSmallIntegerField()),
                ('operator_id', models.PositiveIntegerField()),
                ('operator_login', models.CharField(max_length=50)),
                ('operator_fio', models.CharField(max_length=400)),
                ('group_id', models.PositiveIntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.DateField()),
                ('shift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('aftercall_duration', models.DurationField(default=datetime.timedelta)),
                ('busy_duration', models.DurationField(default=datetime.timedelta)),
                ('hold_duration', models.DurationField(default=datetime.timedelta)),
                ('idle_duration', models.DurationField(default=datetime.timedelta)),
                ('lazy_duration', models.DurationField(default=datetime.timedelta)),
                ('lock_duration', models.DurationField(default=datetime.timedelta)),
                ('relax_duration', models.DurationField(default=datetime.timedelta)),
                ('full_duration', models.DurationField(default=datetime.timedelta)),
                ('is_special_aggregation', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ArchiveGroupSupervisorMap',
        ),
        migrations.DeleteModel(
            name='ArchiveTransferOfWh',
        ),
        migrations.DeleteModel(
            name='ArchiveWorkCompensation',
        ),
        migrations.RemoveIndex(
            model_name='archiveworkdebt',
            name='archive_wor_group_n_72ea6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='archiveworkdebtdetail',
            name='archive_wor_group_n_34ceae_idx',
        ),
        migrations.RenameField(
            model_name='archiveworkdebtdetail',
            old_name='schedule',
            new_name='shift_code',
        ),
        migrations.RenameIndex(
            model_name='archiveworkdebt',
            new_name='archive_arc_archive_98c091_idx',
            old_name='archive_wor_archive_843e62_idx',
        ),
        migrations.RenameIndex(
            model_name='archiveworkdebt',
            new_name='archive_arc_operato_f95462_idx',
            old_name='archive_wor_operato_6677a4_idx',
        ),
        migrations.RenameIndex(
            model_name='archiveworkdebtdetail',
            new_name='archive_arc_archive_f4b4c0_idx',
            old_name='archive_wor_archive_a39d06_idx',
        ),
        migrations.RenameIndex(
            model_name='archiveworkdebtdetail',
            new_name='archive_arc_operato_09522b_idx',
            old_name='archive_wor_operato_38e360_idx',
        ),
        migrations.AlterUniqueTogether(
            name='archiveworkdebt',
            unique_together={('archive_year', 'archive_month', 'operator_id')},
        ),
        migrations.AddField(
            model_name='archiveworkdebt',
            name='final_debt',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Tsikl yopilgan paytdagi qarz'),
        ),
        migrations.AddField(
            model_name='archiveworkdebt',
            name='total_accumulated',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Tsiklda jami berilgan qarz'),
        ),
        migrations.AddField(
            model_name='archiveworkdebtdetail',
            name='make_up_wh',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='archiveworkdebtdetail',
            name='source',
            field=models.CharField(default='shift', max_length=30),
        ),
        migrations.AddField(
            model_name='archiveworkdebtdetail',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archiveworkdebtdetail',
            name='violation_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='archiveworkdebt',
            name='archive_month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='archiveworkdebt',
            name='archive_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='archiveworkdebt',
            name='group_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archiveworkdebt',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archiveworkdebt',
            name='operator_fio',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='archiveworkdebt',
            name='operator_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='archiveworkdebt',
            name='operator_login',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='archiveworkdebtdetail',
            name='archive_month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='archiveworkdebtdetail',
            name='archive_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='archiveworkdebtdetail',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='archiveworkdebtdetail',
            name='group_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archiveworkdebtdetail',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archiveworkdebtdetail',
            name='operator_fio',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='archiveworkdebtdetail',
            name='operator_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='archiveworkdebtdetail',
            name='operator_login',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='archiveworkdebt',
            index=models.Index(fields=['group_id'], name='archive_arc_group_i_5c3a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveworkdebtdetail',
            index=models.Index(fields=['group_id'], name='archive_arc_group_i_adbb75_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveworkdebtdetail',
            index=models.Index(fields=['source'], name='archive_arc_source_4fe2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveworkdebtdetail',
            index=models.Index(fields=['day'], name='archive_arc_day_db127d_idx'),
        ),
        migrations.AlterModelTable(
            name='archiveworkdebt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='archiveworkdebtdetail',
            table=None,
        ),
        migrations.AddIndex(
            model_name='archivecompensation',
            index=models.Index(fields=['archive_year', 'archive_month'], name='archive_arc_archive_f35c45_idx'),
        ),
        migrations.AddIndex(
            model_name='archivecompensation',
            index=models.Index(fields=['operator_id', 'planned_date'], name='archive_arc_operato_b36271_idx'),
        ),
        migrations.AddIndex(
            model_name='archivecompensation',
            index=models.Index(fields=['group_id'], name='archive_arc_group_i_da1734_idx'),
        ),
        migrations.AddIndex(
            model_name='archivecompensation',
            index=models.Index(fields=['status'], name='archive_arc_status_b8f9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='archivecompensation',
            index=models.Index(fields=['original_id'], name='archive_arc_origina_c525e4_idx'),
        ),
        migrations.AddIndex(
            model_name='archivecompensation',
            index=models.Index(fields=['source'], name='archive_arc_source_8fcc58_idx'),
        ),
        migrations.AddIndex(
            model_name='archivecycle',
            index=models.Index(fields=['year', 'month'], name='archive_arc_year_3826cc_idx'),
        ),
        migrations.AddIndex(
            model_name='archivecycle',
            index=models.Index(fields=['end_date'], name='archive_arc_end_dat_72ce64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='archivecycle',
            unique_together={('year', 'month')},
        ),
        migrations.AddIndex(
            model_name='archiveeventlog',
            index=models.Index(fields=['archive_year', 'archive_month'], name='archive_arc_archive_d08958_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveeventlog',
            index=models.Index(fields=['event_type'], name='archive_arc_event_t_50d6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveeventlog',
            index=models.Index(fields=['level'], name='archive_arc_level_9d8ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveeventlog',
            index=models.Index(fields=['operator_id'], name='archive_arc_operato_948b24_idx'),
        ),
        migrations.AddIndex(
            model_name='archivemanualadjustment',
            index=models.Index(fields=['archive_year', 'archive_month'], name='archive_arc_archive_f885c8_idx'),
        ),
        migrations.AddIndex(
            model_name='archivemanualadjustment',
            index=models.Index(fields=['operator_id'], name='archive_arc_operato_34c678_idx'),
        ),
        migrations.AddIndex(
            model_name='archivemanualadjustment',
            index=models.Index(fields=['adjusted_by_id'], name='archive_arc_adjuste_a965fb_idx'),
        ),
        migrations.AddIndex(
            model_name='archivemanualadjustment',
            index=models.Index(fields=['target_type', 'target_id'], name='archive_arc_target__070e78_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveoperatorsnapshot',
            index=models.Index(fields=['archive_year', 'archive_month'], name='archive_arc_archive_965856_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveoperatorsnapshot',
            index=models.Index(fields=['operator_id'], name='archive_arc_operato_6cfae8_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveoperatorsnapshot',
            index=models.Index(fields=['operator_login'], name='archive_arc_operato_ada3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveoperatorsnapshot',
            index=models.Index(fields=['group_id'], name='archive_arc_group_i_ee664d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='archiveoperatorsnapshot',
            unique_together={('archive_year', 'archive_month', 'operator_id')},
        ),
        migrations.AddIndex(
            model_name='archivetransfer',
            index=models.Index(fields=['archive_year', 'archive_month'], name='archive_arc_archive_dd793f_idx'),
        ),
        migrations.AddIndex(
            model_name='archivetransfer',
            index=models.Index(fields=['operator_id', 'date_from'], name='archive_arc_operato_803507_idx'),
        ),
        migrations.AddIndex(
            model_name='archivetransfer',
            index=models.Index(fields=['operator_id', 'date_to'], name='archive_arc_operato_39a995_idx'),
        ),
        migrations.AddIndex(
            model_name='archivetransfer',
            index=models.Index(fields=['group_id'], name='archive_arc_group_i_147f01_idx'),
        ),
        migrations.AddIndex(
            model_name='archivetransfer',
            index=models.Index(fields=['type_code'], name='archive_arc_type_co_622111_idx'),
        ),
        migrations.AddIndex(
            model_name='archivetransfer',
            index=models.Index(fields=['status'], name='archive_arc_status_de11f7_idx'),
        ),
        migrations.AddIndex(
            model_name='archivetransfer',
            index=models.Index(fields=['original_id'], name='archive_arc_origina_607fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveworklogdaily',
            index=models.Index(fields=['archive_year', 'archive_month'], name='archive_arc_archive_f264ed_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveworklogdaily',
            index=models.Index(fields=['operator_id', 'day'], name='archive_arc_operato_8428d1_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveworklogdaily',
            index=models.Index(fields=['day'], name='archive_arc_day_854a96_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveworklogdaily',
            index=models.Index(fields=['group_id'], name='archive_arc_group_i_23e610_idx'),
        ),
        migrations.RemoveField(
            model_name='archiveworkdebt',
            name='total_debt',
        ),
        migrations.RemoveField(
            model_name='archiveworkdebt',
            name='total_debt_accumulated',
        ),
        migrations.RemoveField(
            model_name='archiveworkdebt',
            name='total_debt_day',
        ),
        migrations.RemoveField(
            model_name='archiveworkdebt',
            name='total_debt_hour',
        ),
    ]
