# Generated by Django 5.2.6 on 2026-05-29 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archivecompensation_archivecycle_archiveeventlog_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='archivecompensation',
            name='archive_arc_group_i_da1734_idx',
        ),
        migrations.RemoveIndex(
            model_name='archiveoperatorsnapshot',
            name='archive_arc_group_i_ee664d_idx',
        ),
        migrations.RemoveIndex(
            model_name='archivetransfer',
            name='archive_arc_group_i_147f01_idx',
        ),
        migrations.RemoveIndex(
            model_name='archiveworkdebt',
            name='archive_arc_group_i_5c3a8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='archiveworkdebtdetail',
            name='archive_arc_group_i_adbb75_idx',
        ),
        migrations.RemoveIndex(
            model_name='archiveworklogdaily',
            name='archive_arc_group_i_23e610_idx',
        ),
        migrations.AlterField(
            model_name='archivecompensation',
            name='debt_links_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='archivecompensation',
            name='original_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='archivecompensation',
            name='source',
            field=models.CharField(default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='archivetransfer',
            name='was_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archiveworkdebt',
            name='final_debt',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='archiveworkdebt',
            name='total_accumulated',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
