# Generated by Django 5.2.6 on 2026-04-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hourly_locks', '0036_alter_operator_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('scheduled_start', models.DateTimeField()),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('absent', 'Absent')], max_length=10)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='hourly_locks.operator')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='attendance__date_bddb55_idx'), models.Index(fields=['status'], name='attendance__status_018901_idx')],
                'unique_together': {('operator', 'date')},
            },
        ),
    ]
